### ISSUE TITLE
Connection with CLDR

### ISSUE THREAD

**Issue by Louis-Aime** [tc39/proposal-intl-eradisplay#2]
The eraDisplay proposal came initially from [a ticket at CLDR](https://unicode-org.atlassian.net/browse/CLDR-13671) where I was worried that era field was displayed even if the author did not explicitly ask for it. This post is still in "new" state the day I'am writing this post. Seeing no reaction, I designed the first draft of the eraDisplay proposal in May 2020.

The presently distributed version of CLDR reacts in different ways when `era` option is not defined where `year` is. These is quite visible and easy to test on the [proposal's moke-up on GitHub Pages](https://louis-aime.github.io/proposal-intl-eradisplay/). With "en-GB", when `era` is set to `undefined` for `ethiopic` or `coptic`, display is as if `month` was `undefined` ! 

I suspect there are certain "shortcuts" in designing the date display patterns that yield to unwanted effects.

I intend to issue a new post on CLDR on this issue.

**Comment by Louis-Aime** [comment]
Post initially on CLDR, now on ICU: [ICU-21428](https://unicode-org.atlassian.net/browse/ICU-21428)

**Comment by sffc** [comment]
@eggrobin is working on improved date skeleton resolution separately in CLDR, which should help to resolve this. See https://docs.google.com/document/d/1dQOw-U1IajwpHYdP08bG55JY6pqRlhjz2fZJ0vDHcBU/edit#heading=h.19l2he9jii8u
