### ISSUE TITLE
Transfer to tc39 org

### ISSUE THREAD

**Issue by sffc** [tc39/proposal-intl-eradisplay#6]
The proposal has been accepted as Stage 1.  This means that we should migrate this repo from `Louis-Aime/proposal-intl-eradisplay` to `tc39/proposal-intl-eradisplay`.

The first step is to transfer the repo to me, and then I will move it to tc39.

**Comment by Louis-Aime** [comment]
Got stage 1, great news. @sffc  I just transferred this repo to you.
